steps:
  - checkout: self
    submodules: true
    persistCredentials: true

  - bash: |
      echo "archivaUserName=$(ARCHIVA_USERNAME)" >> gradle.properties
      echo "archivaPassword=$(ARCHIVA_PASSWORD)" >> gradle.properties
      echo "WASADMIN_USER=$(WASADMIN_USER)" >> ./deploy/wasenv.sh
      echo "WASADMIN_PASSWORD=$(WASADMIN_PASSWORD)" >> ./deploy/wasenv.sh
      chmod ugo+x ./deploy/wasenv.sh

  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'assembleDist'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false