# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develops

pool:
  vmImage: ubuntu-latest

  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: 'AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBC7Jjdz2LqyM3femuSllOAlxvLn7iDyhiVtpNmKV/kSaS4g1egVzf5OkfShhEu54ESICkWLdOsCZ/Px8QHKz6XU='
      sshKeySecureFile: 'azure_develop_deploy'
      configUser: azure-deploy

  # Include the common steps for building the console app
  - template: azure-pipelines.common.yml

  - task: CmdLine@2
    inputs:
      script: 'mv ./common.env ./common.env'

  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'console.sharptree.io'
      sourceFolder: './build/distributions'
      contents: 'barcode-print-*.tar.gz'
      targetFolder: './'
      readyTimeout: '20000'
  - task: SSH@0
    inputs:
      sshEndpoint: 'console.sharptree.io'
      runOptions: 'inline'
      inline: |
        cp -R /home/azure-deploy/web /srv/console/
        rm -R /home/azure-deploy/web/
      failOnStdErr: false
      readyTimeout: '20000'
